_target_: schnetpack.representation.SymmetryFunctions
radial:
  _target_: schnetpack.representation.symfuncs.RadialSF
  radial_basis:
    _target_: schnetpack.nn.radial.GaussianRBF
    n_rbf: 5
    cutoff: 5.0
  elemental_basis:
    _target_: schnetpack.nn.symmetry_functions.OneHotElements
    elements:
      - 1
      - 6
      - 8
  cutoff_fn:
    _target_: schnetpack.nn.cutoff.CosineCutoff
    cutoff: ${model.representation.radial.radial_basis.cutoff}
angular:
  _target_: schnetpack.representation.symfuncs.AngularSFANI
  radial_basis:
    _target_: schnetpack.nn.radial.GaussianRBF
    n_rbf: 3
    cutoff: 5.0
  elemental_basis:
    _target_: schnetpack.nn.symmetry_functions.OneHotElements
    elements:
      - 1
      - 6
      - 8
  angular_basis:
    _target_: schnetpack.nn.symmetry_functions.AngularBasisANI
    n_abf:
      5
    zetas:
      - 1
  cutoff_fn:
    _target_: schnetpack.nn.cutoff.CosineCutoff
    cutoff: ${model.representation.radial.radial_basis.cutoff}
