_target_: schnetpack.md.calculators.OrcaCalculator
required_properties:
  - energy
  - forces
force_key: forces
compdir: qm_calculations
qm_executable: ???
orca_template: ???
energy_unit: Hartree
position_unit: Bohr
energy_key: energy
stress_key: null
property_conversion: { }
overwrite: true
adaptive: false
basename: qm_calc
