_target_: schnetpack.md.calculators.SchnetPackCalculator
required_properties:
  - energy
  - forces
model_file: ???
force_label: forces
energy_units: kcal / mol
position_units: Angstrom
energy_label: energy
stress_label: null
script_model: true

defaults:
  neighbor_list: ase