_target_: schnetpack.md.calculators.SchNetPackEnsembleCalculator
required_properties:
  - energy
  - forces
model_files:
  - ???
force_label: forces
energy_units: kcal / mol
position_units: Angstrom
energy_label: energy
stress_label: null
script_model: false

defaults:
  - neighbor_list: ase
