[tox]
envlist = py38,qa

[testenv]
deps =
    pytest
    pytest-cov
    pytest-datadir
commands =
    pip install -e .[doc,test]
    pip list
    pytest --cov-report term --cov=schnetpack

# prevent exit when error is encountered
ignore_errors = true

[testenv:qa]
commands =
    pip install -e .[dev]
    black -v -l 88 --check --diff src/schnetpack
# prevent exit when error is encountered
ignore_errors = true
