early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_loss"      # name of the logged metric which determines when model is improving
  patience: 200           # how many epochs of not improving until training stops
  mode: "min"             # can be "max" or "min"
  min_delta: 0.0         # minimum change in the monitored metric needed to qualify as an improvement
  check_on_train_epoch_end: False