defaults:
  - representation: schnet

_target_: schnetpack.model.PESModel

optimizer:
  _target_: torch.optim.Adam
  args:
    lr: ${lr}

scheduler:
  monitor: val_loss_fn
  _target_: schnetpack.train.ReduceLROnPlateau
  args:
    mode: min
    factor: 0.5
    patience: 50
    min_lr: 1e-6
    smoothing_factor: 0.8

output:
  _target_: schnetpack.atomistic.Atomwise
  n_in: ${model.representation.n_atom_basis}
  aggregation_mode: sum

#  normalization:
#    initialize_with_stats: True
#    requires_atomref: False

energy_property: energy
energy_loss_fn:
  _target_: pytorch_lightning.metrics.MeanSquaredError
energy_weight: 0.05
energy_metrics:
  mae:
    _target_: pytorch_lightning.metrics.MeanAbsoluteError
  mse:
    _target_: pytorch_lightning.metrics.MeanSquaredError

forces_property: forces
forces_loss_fn:
  _target_: pytorch_lightning.metrics.MeanSquaredError
forces_weight: 0.90
forces_metrics:
  mae:
    _target_: pytorch_lightning.metrics.MeanAbsoluteError
  mse:
    _target_: pytorch_lightning.metrics.MeanSquaredError

stress_property: stress
stress_loss_fn:
  _target_: pytorch_lightning.metrics.MeanSquaredError
stress_weight: 0.05
stress_metrics:
  mae:
    _target_: pytorch_lightning.metrics.MeanAbsoluteError
  mse:
    _target_: pytorch_lightning.metrics.MeanSquaredError

postprocess: null