defaults:
  - pes

output_modules:
  - _target_: schnetpack.atomistic.Atomwise
    output: ${energy_key}
    n_in: ${model.representation.n_atom_basis}
    aggregation_mode: sum
  - _target_: schnetpack.atomistic.Forces
    energy_key: ${energy_key}
    force_key: ${forces_key}
    stress_key: ${stress_key}

outputs:
  - _target_: schnetpack.atomistic.ModelOutput
    name: ${energy_key}
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 0.05
  - _target_: schnetpack.atomistic.ModelOutput
    name: ${forces_key}
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 0.90
  - _target_: schnetpack.atomistic.ModelOutput
    name: ${stress_key}
    loss_fn:
      _target_: torch.nn.MSELoss
    metrics:
      mae:
        _target_: torchmetrics.regression.MeanAbsoluteError
      mse:
        _target_: torchmetrics.regression.MeanSquaredError
    loss_weight: 0.05
