_target_: schnetpack.md.neighborlist_md.NeighborListMD
cutoff: ???
cutoff_shell: 2.0
requires_triples: false
base_nbl: schnetpack.transform.TorchNeighborList
collate_fn: schnetpack.data.loader._atoms_collate_fn