# @package task
scheduler_cls: schnetpack.train.ReduceLROnPlateau
scheduler_monitor: val_loss
scheduler_args:
  mode: min
  factor: 0.5
  patience: 75
  threshold: 0.0
  threshold_mode: rel
  cooldown: 10
  min_lr: 0.0
  smoothing_factor: 0.0