# @package _global_

defaults:
  - train_base
  - override /model: single_property
  - override /data: ani1

cutoff: 5.0
n_rbf: 20
lr: 1e-3

property: energy
name: ani1_${property}

data:
  distance_unit: Ang
  property_units:
    energy: eV
  transforms:
    - _target_: schnetpack.transform.SubtractCenterOfMass
    - _target_: schnetpack.transform.RemoveOffsets
      property: ${property}
      remove_atomrefs: True
      remove_mean: True
    - _target_: schnetpack.transform.ASENeighborList
      cutoff: ${cutoff}
    - _target_: schnetpack.transform.CastTo32

model:
  postprocess:
    - _target_: schnetpack.transform.CastTo64
    - _target_: schnetpack.transform.AddOffsets
      property: ${property}
      add_mean: True
      add_atomrefs: True

